apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      # Add security context for the pod
      securityContext:
        fsGroup: 2000
      initContainers:
      - name: init-fluentd-positions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/log/fluentd/positions && chmod 777 /var/log/fluentd/positions']
        volumeMounts:
        - name: fluentd-positions
          mountPath: /var/log/fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: grafana/fluent-plugin-loki:latest
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: FLUENT_LOKI_HOST
            value: "loki"
          - name: FLUENT_LOKI_PORT
            value: "3100"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: fluentd-positions
          mountPath: /var/log/fluentd
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: fluentd-positions
        emptyDir: {}