apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/fastapi-app-backend*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.fastapi.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <source>
      @type tail
      path /var/log/containers/mongodb*.log
      pos_file /var/log/fluentd-mongodb.log.pos
      tag kubernetes.mongodb.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      kubernetes_url https://kubernetes.default.svc
      verify_ssl false
    </filter>

    <match kubernetes.**>
      @type loki
      url "http://loki:3100"
      extra_labels {"job":"fluentd"}
      flush_interval 10s
      flush_at_shutdown true
      buffer_chunk_limit 1m
    </match>